In [1]:
import numpy as np

In [2]:
def Print_Board(board):

    print("\n-------------------------")

    for i in range(9):
        for j in range(9):
            if board[i, j] != 0:
                if j == 0:
                    print("|", end=" ")
                print(f"{board[i, j]} ", end="")
            else:
                if j == 0:
                    print("|", end=" ")
                print("  ", end="")
            if (j + 1) % 3 == 0:
                print("|", end=" ")
        if (i + 1) % 3 == 0:
            print("\n-------------------------", end=" ")
        print()
        


In [3]:
def domain_check(var): #checks if a variable is in the domain
    domain = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
    return np.any(domain == var)

#example
domain_check(8)

True

In [4]:
#costraints
def constrain(value, x, y, matrix):
    #first checks if the value is in the domain
    if domain_check(value):
        
        #assigne a value not correct to not return false
        var = matrix[x, y]
        matrix[x, y] = -1
        
        #costrain submatrix
        submatrix = matrix[x//3*3:x//3*3+3, y//3*3:y//3*3+3]
        if np.any(submatrix == value):
            matrix[x, y] = var
            return False  
        
        #costrain column
        if np.any(matrix[:, y] == value):
            matrix[x, y] = var
            return False
        
        #costrain row
        if np.any(matrix[x, :] == value):
            matrix[x, y] = var
            return False 
        
        matrix[x, y] = var
        return True
    else:
        return False



In [5]:
#checks if the matrix is correct
def goal_matrix(matrix):
    
    if matrix.item(0) == -1:
        return False
    
    for x in range(9):
        for y in range(9):
            if constrain(matrix[x, y], x, y, matrix) == False & matrix[x, y] == 0:
                return False
    return True


In [6]:

def domain(x, y, matrix):
    domain = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
    for val in domain:        
        if constrain(val, x, y, matrix) == False:
            index = np.argwhere(domain==val)
            domain = np.delete(domain, index)
            
    return domain

In [7]:
#return a matrix with all elements that can be assigned in that cell
def create_assign_matrix(matrix):
    assign = np.zeros(shape=(9, 9), dtype=object)
    for i in range(9):
        for j in range(9):
            if matrix[i, j] == 0:
                assign[i, j] = domain(i, j, matrix)
            else:
                assign[i, j] = np.array([matrix[i, j]])
    return assign


a = np.matrix([[3, 7, 0, 5, 0, 0, 0, 0, 6], 
               [0, 0, 0, 3, 6, 0, 0, 1, 2],
               [0, 0, 0, 0, 9, 1, 7, 5, 0],
               [0, 0, 0, 1, 5, 4, 0, 7, 0],
               [0, 0, 3, 0, 7, 0, 6, 0, 0], 
               [0, 5, 0, 6, 3, 8, 0, 0, 0], 
               [0, 6, 4, 9, 8, 0, 0, 0, 0],
               [5, 9, 0, 0, 2, 6, 0, 0, 0],
               [2, 0, 0, 0, 0, 5, 0, 6, 4]])
assign = create_assign_matrix(a)

In [8]:
def error(assign):
    for i in range(9):
        for j in range(9):
            if assign[i, j].size==0:
                return True
    return False

In [9]:
#return a new assign_matrix adjusted to the removed element
def remove_element_from_assign_matrix(val, x, y, assign):
    new_assign = assign.copy()
    for i in range(9):
        if np.any(assign[x, i]==val):
            index = np.argwhere(assign[x, i]==val)
            new_assign[x, i] = np.delete(assign[x, i], index)
    for j in range(9):
        if np.any(assign[j, y]==val):
            index = np.argwhere(assign[j, y]==val)
            new_assign[j, y] = np.delete(assign[j, y], index)
                
    for i in range(x//3*3,x//3*3+3):
        for j in range(y//3*3,y//3*3+3):  
            if np.any(assign[i, j]==val):
                index = np.argwhere(assign[i, j]==val)
                new_assign[i, j] = np.delete(assign[i, j], index)
            
    new_assign[x, y] = np.array([val])
    return new_assign
                    
ass = remove_element_from_assign_matrix(8, 4, 4, assign)
print(ass)
error(ass)

[[array([3]) array([7]) array([1, 2, 8, 9]) array([5]) array([4])
  array([2]) array([4, 8, 9]) array([4, 8, 9]) array([6])]
 [array([4, 8, 9]) array([4, 8]) array([5, 8, 9]) array([3]) array([6])
  array([7]) array([4, 8, 9]) array([1]) array([2])]
 [array([4, 6, 8]) array([2, 4, 8]) array([2, 6, 8]) array([2, 4, 8])
  array([9]) array([1]) array([7]) array([5]) array([3, 8])]
 [array([6, 8, 9]) array([2, 8]) array([2, 6, 8, 9]) array([1])
  array([5]) array([4]) array([2, 3, 8, 9]) array([7]) array([3, 8, 9])]
 [array([1, 4, 9]) array([1, 2, 4]) array([3]) array([2]) array([8])
  array([2, 9]) array([6]) array([2, 4, 9]) array([1, 5, 9])]
 [array([1, 4, 7, 9]) array([5]) array([1, 2, 7, 9]) array([6])
  array([3]) array([], dtype=int32) array([1, 2, 4, 9]) array([2, 4, 9])
  array([1, 9])]
 [array([1, 7]) array([6]) array([4]) array([9]) array([], dtype=int32)
  array([3, 7]) array([1, 2, 3, 5]) array([2, 3]) array([1, 3, 5, 7])]
 [array([5]) array([9]) array([1, 7, 8]) array([4, 7])

True

In [10]:
def create_list(matrix, assign):
    l = []
    for i in range(9):
        for j in range(9):
            if matrix[i, j] == 0:
                l +=  [{'index': [i, j], 'len': assign[i, j].size}]
    return l
a = np.matrix([[3, 7, 0, 5, 0, 0, 0, 0, 6], 
               [0, 0, 0, 3, 6, 0, 0, 1, 2],
               [0, 0, 0, 0, 9, 1, 7, 5, 0],
               [0, 0, 0, 1, 5, 4, 0, 7, 0],
               [0, 0, 3, 0, 7, 0, 6, 0, 0], 
               [0, 5, 0, 6, 3, 8, 0, 0, 0], 
               [0, 6, 4, 9, 8, 0, 0, 0, 0],
               [5, 9, 0, 0, 2, 6, 0, 0, 0],
               [2, 0, 0, 0, 0, 5, 0, 6, 4]])
assign = create_assign_matrix(a)
l = create_list(a, assign)


def order_by_len(e):
    return e['len']
l.sort(key=order_by_len)
l.pop(0).get('index')




[0, 4]

In [11]:
def solve_sudoku(sudoku, assign, step):
    #list with all variables (empty cells)
    list_of_var = create_list(sudoku, assign) 
    
    #if we don't have any variables, we reach our goal state
    if len(list_of_var) == 0:  
        return True
    
    #minimum remaining value heuristic
    #sort the list by len of the domain for each variable
    list_of_var.sort(key=order_by_len)
    #pop the first element of the list(element)
    index = list_of_var.pop(0).get('index')    
    
    #domain of the variable
    domain = assign[index[0], index[1]]
    
    #number of recursive steps to solve the sudoku
    step[0] +=1
    
    #Forward Checking
    for val in domain:
        
        
        #assign the first element of the list        
        new_assign = remove_element_from_assign_matrix(domain[0], index[0], index[1] , assign)
        
        #check if there are any empty cells
        if error(new_assign) == False:
            sudoku[index[0], index[1]] = val 
            new_assign = create_assign_matrix(sudoku)
            
            #check if this new state we will find a solution
            if solve_sudoku(sudoku, new_assign, step):  
                #if we have a solution, then return true
                assign = new_assign   
                return True
            else:
                sudoku[index[0], index[1]] = 0
    
    #return failure, we didn't find any solution, so we need to backtrack
    return False

In [12]:
#example n1:
from datetime import datetime

test0 = np.matrix([[3, 7, 0, 5, 0, 0, 0, 0, 6], 
               [0, 0, 0, 3, 6, 0, 0, 1, 2],
               [0, 0, 0, 0, 9, 1, 7, 5, 0],
               [0, 0, 0, 1, 5, 4, 0, 7, 0],
               [0, 0, 3, 0, 7, 0, 6, 0, 0], 
               [0, 5, 0, 6, 3, 8, 0, 0, 0], 
               [0, 6, 4, 9, 8, 0, 0, 0, 0],
               [5, 9, 0, 0, 2, 6, 0, 0, 0],
               [2, 0, 0, 0, 0, 5, 0, 6, 4]])

Print_Board(test0)

assign = create_assign_matrix(test0)
start_time = datetime.now()
step = [0]

solve_sudoku(test0, assign, step)

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

if goal_matrix(test0):
    print("Sudoku Completed")
    print ("Solution found in %s steps, "%(step[0]))
else:
    print("Solution Not Found")


Print_Board(test0)


-------------------------
| 3 7   | 5     |     6 | 
|       | 3 6   |   1 2 | 
|       |   9 1 | 7 5   | 
------------------------- 
|       | 1 5 4 |   7   | 
|     3 |   7   | 6     | 
|   5   | 6 3 8 |       | 
------------------------- 
|   6 4 | 9 8   |       | 
| 5 9   |   2 6 |       | 
| 2     |     5 |   6 4 | 
------------------------- 
Duration: 0:00:00.800324
Sudoku Completed
Solution found in 46 steps, 

-------------------------
| 3 7 1 | 5 4 2 | 8 9 6 | 
| 9 8 5 | 3 6 7 | 4 1 2 | 
| 6 4 2 | 8 9 1 | 7 5 3 | 
------------------------- 
| 8 2 6 | 1 5 4 | 3 7 9 | 
| 4 1 3 | 2 7 9 | 6 8 5 | 
| 7 5 9 | 6 3 8 | 2 4 1 | 
------------------------- 
| 1 6 4 | 9 8 3 | 5 2 7 | 
| 5 9 7 | 4 2 6 | 1 3 8 | 
| 2 3 8 | 7 1 5 | 9 6 4 | 
------------------------- 


In [13]:
import numpy as np
from datetime import datetime


test1 = np.matrix([[0, 1, 6, 3, 0, 8, 4, 2, 0], 
                   [8, 4, 0, 0, 0, 7, 3, 0, 0],
                   [3, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 6, 0, 9, 4, 0, 8, 0, 2],
                   [0, 8, 1, 0, 3, 0, 7, 9, 0], 
                   [9, 0, 3, 0, 7, 6, 0, 4, 0], 
                   [0, 0, 0, 0, 0, 0, 0, 0, 3],
                   [0, 0, 5, 7, 0, 0, 0, 6, 8],
                   [0, 7, 8, 1, 0, 3, 2, 5, 0]])
Print_Board(test1)

assign = create_assign_matrix(test1)
start_time = datetime.now()
step = [0]

solve_sudoku(test1, assign, step)

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

if goal_matrix(test1):
    print("Sudoku Completed")
    print ("Solution found in %s steps, "%(step[0]))
else:
    print("Solution Not Found")


Print_Board(test1)


-------------------------
|   1 6 | 3   8 | 4 2   | 
| 8 4   |     7 | 3     | 
| 3     |       |       | 
------------------------- 
|   6   | 9 4   | 8   2 | 
|   8 1 |   3   | 7 9   | 
| 9   3 |   7 6 |   4   | 
------------------------- 
|       |       |     3 | 
|     5 | 7     |   6 8 | 
|   7 8 | 1   3 | 2 5   | 
------------------------- 
Duration: 0:00:00.611177
Sudoku Completed
Solution found in 44 steps, 

-------------------------
| 7 1 6 | 3 5 8 | 4 2 9 | 
| 8 4 9 | 2 6 7 | 3 1 5 | 
| 3 5 2 | 4 1 9 | 6 8 7 | 
------------------------- 
| 5 6 7 | 9 4 1 | 8 3 2 | 
| 4 8 1 | 5 3 2 | 7 9 6 | 
| 9 2 3 | 8 7 6 | 5 4 1 | 
------------------------- 
| 2 9 4 | 6 8 5 | 1 7 3 | 
| 1 3 5 | 7 2 4 | 9 6 8 | 
| 6 7 8 | 1 9 3 | 2 5 4 | 
------------------------- 


In [14]:
import numpy as np
from datetime import datetime


test2 = np.matrix([[0, 0, 2, 0, 3, 0, 0, 0, 8], 
                   [0, 0, 0, 0, 0, 8, 0, 0, 0],
                   [0, 3, 1, 0, 2, 0, 0, 0, 0],
                   [0, 6, 0, 0, 5, 0, 2, 7, 0],
                   [0, 1, 0, 0, 0, 0, 0, 5, 0], 
                   [2, 0, 4, 0, 6, 0, 0, 3, 1], 
                   [0, 0, 0, 0, 8, 0, 6, 0, 5],
                   [0, 0, 0, 0, 0, 0, 0, 1, 3],
                   [0, 0, 5, 3, 1, 0, 4, 0, 0]])
Print_Board(test2)
assign = create_assign_matrix(test2)

step = [0]

start_time = datetime.now()

solve_sudoku(test2,assign, step)

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

if goal_matrix(test2):
    print("Sudoku Completed")
    print ("Solution found in %s steps, "%(step[0]))
else:
    print("Solution Not Found")


Print_Board(test2)


-------------------------
|     2 |   3   |     8 | 
|       |     8 |       | 
|   3 1 |   2   |       | 
------------------------- 
|   6   |   5   | 2 7   | 
|   1   |       |   5   | 
| 2   4 |   6   |   3 1 | 
------------------------- 
|       |   8   | 6   5 | 
|       |       |   1 3 | 
|     5 | 3 1   | 4     | 
------------------------- 
Duration: 0:00:02.611870
Sudoku Completed
Solution found in 137 steps, 

-------------------------
| 6 7 2 | 4 3 5 | 1 9 8 | 
| 5 4 9 | 1 7 8 | 3 6 2 | 
| 8 3 1 | 6 2 9 | 5 4 7 | 
------------------------- 
| 3 6 8 | 9 5 1 | 2 7 4 | 
| 9 1 7 | 2 4 3 | 8 5 6 | 
| 2 5 4 | 8 6 7 | 9 3 1 | 
------------------------- 
| 1 9 3 | 7 8 4 | 6 2 5 | 
| 4 8 6 | 5 9 2 | 7 1 3 | 
| 7 2 5 | 3 1 6 | 4 8 9 | 
------------------------- 


In [15]:
import numpy as np
from datetime import datetime


test3 = np.matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0], 
                   [0, 0, 8, 0, 0, 0, 0, 4, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 6, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0], 
                   [0, 0, 0, 0, 0, 0, 0, 0, 0], 
                   [2, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 2, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0]])
Print_Board(test3)
assign = create_assign_matrix(test2)

start_time = datetime.now()
step = [0]
solve_sudoku(test3,assign, step)

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

if goal_matrix(test3):
    print("Sudoku Completed")
    print ("Solution found in %s steps, "%(step[0]))
else:
    print("Solution Not Found")


Print_Board(test3)


-------------------------
|       |       |       | 
|     8 |       |   4   | 
|       |       |       | 
------------------------- 
|       |     6 |       | 
|       |       |       | 
|       |       |       | 
------------------------- 
| 2     |       |       | 
|       |       | 2     | 
|       |       |       | 
------------------------- 
Duration: 0:00:02.044335
Sudoku Completed
Solution found in 76 steps, 

-------------------------
| 6 4 5 | 7 8 9 | 1 2 3 | 
| 1 2 8 | 5 6 3 | 7 4 9 | 
| 3 7 9 | 1 2 4 | 5 6 8 | 
------------------------- 
| 8 1 2 | 4 7 6 | 3 9 5 | 
| 5 6 7 | 3 9 8 | 4 1 2 | 
| 9 3 4 | 2 1 5 | 6 8 7 | 
------------------------- 
| 2 5 6 | 9 3 1 | 8 7 4 | 
| 4 9 1 | 8 5 7 | 2 3 6 | 
| 7 8 3 | 6 4 2 | 9 5 1 | 
------------------------- 


In [16]:
import numpy as np
from datetime import datetime


test4 = np.matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0], 
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0], 
                   [0, 0, 0, 0, 0, 0, 0, 0, 0], 
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0]])
Print_Board(test4)
assign = create_assign_matrix(test4)

step = [0]
start_time = datetime.now()

solve_sudoku(test4, assign, step)

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

if goal_matrix(test4):
    print("Sudoku Completed")
    print ("Solution found in %s steps, "%(step[0]))
else:
    print("Solution Not Found")


Print_Board(test4)


-------------------------
|       |       |       | 
|       |       |       | 
|       |       |       | 
------------------------- 
|       |       |       | 
|       |       |       | 
|       |       |       | 
------------------------- 
|       |       |       | 
|       |       |       | 
|       |       |       | 
------------------------- 
Duration: 0:00:02.183485
Sudoku Completed
Solution found in 81 steps, 

-------------------------
| 1 2 3 | 4 5 6 | 7 8 9 | 
| 4 5 6 | 7 8 9 | 1 2 3 | 
| 7 8 9 | 1 2 3 | 4 5 6 | 
------------------------- 
| 2 3 1 | 6 7 4 | 8 9 5 | 
| 8 7 5 | 9 1 2 | 3 6 4 | 
| 6 9 4 | 5 3 8 | 2 1 7 | 
------------------------- 
| 3 1 7 | 2 6 5 | 9 4 8 | 
| 5 4 2 | 8 9 7 | 6 3 1 | 
| 9 6 8 | 3 4 1 | 5 7 2 | 
------------------------- 


In [17]:
import numpy as np
from datetime import datetime



test5 = np.matrix([[0, 2, 0, 0, 0, 0, 0, 0, 0], 
                   [0, 0, 0, 6, 0, 0, 0, 0, 3],
                   [0, 7, 4, 0, 8, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 3, 0, 0, 2],
                   [0, 8, 0, 0, 4, 0, 0, 1, 0], 
                   [6, 0, 0, 5, 0, 0, 0, 0, 0], 
                   [0, 0, 0, 0, 1, 0, 7, 8, 0],
                   [5, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 9, 0, 4, 0]])
Print_Board(test5)
assign = create_assign_matrix(test5)

step = [0]
start_time = datetime.now()

solve_sudoku(test5, assign, step)

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

if goal_matrix(test5):
    print("Sudoku Completed")
    print ("Solution found in %s steps, "%(step[0]))
else:
    print("Solution Not Found")


Print_Board(test5)


-------------------------
|   2   |       |       | 
|       | 6     |     3 | 
|   7 4 |   8   |       | 
------------------------- 
|       |     3 |     2 | 
|   8   |   4   |   1   | 
| 6     | 5     |       | 
------------------------- 
|       |   1   | 7 8   | 
| 5     |       |       | 
|       |     9 |   4   | 
------------------------- 
Duration: 0:01:23.853386
Sudoku Completed
Solution found in 3183 steps, 

-------------------------
| 8 2 6 | 1 3 7 | 9 5 4 | 
| 1 9 5 | 6 2 4 | 8 7 3 | 
| 3 7 4 | 9 8 5 | 1 2 6 | 
------------------------- 
| 7 5 1 | 8 9 3 | 4 6 2 | 
| 9 8 3 | 2 4 6 | 5 1 7 | 
| 6 4 2 | 5 7 1 | 3 9 8 | 
------------------------- 
| 4 6 9 | 3 1 2 | 7 8 5 | 
| 5 1 7 | 4 6 8 | 2 3 9 | 
| 2 3 8 | 7 5 9 | 6 4 1 | 
------------------------- 


In [18]:
import numpy as np
from datetime import datetime



test6 = np.matrix([[8, 0, 0, 0, 0, 0, 0, 0, 0], 
                   [0, 0, 3, 6, 0, 0, 0, 0, 0],
                   [0, 7, 0, 0, 9, 0, 2, 0, 0],
                   [0, 5, 0, 0, 0, 7, 0, 0, 0],
                   [0, 0, 0, 0, 4, 5, 7, 0, 0], 
                   [0, 0, 0, 1, 0, 0, 0, 3, 0], 
                   [0, 0, 1, 0, 0, 0, 0, 6, 8],
                   [0, 0, 8, 5, 0, 0, 0, 1, 0],
                   [0, 9, 0, 0, 0, 0, 4, 0, 0]])
Print_Board(test6)
assign = create_assign_matrix(test6)

step = [0]

start_time = datetime.now()

solve_sudoku(test6, assign, step)


end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

if goal_matrix(test6):
    print("Sudoku Completed")
    print ("Solution found in %s steps, "%(step[0]))
else:
    print("Solution Not Found")


Print_Board(test6)


-------------------------
| 8     |       |       | 
|     3 | 6     |       | 
|   7   |   9   | 2     | 
------------------------- 
|   5   |     7 |       | 
|       |   4 5 | 7     | 
|       | 1     |   3   | 
------------------------- 
|     1 |       |   6 8 | 
|     8 | 5     |   1   | 
|   9   |       | 4     | 
------------------------- 
Duration: 0:03:34.200702
Sudoku Completed
Solution found in 9179 steps, 

-------------------------
| 8 1 2 | 7 5 3 | 6 4 9 | 
| 9 4 3 | 6 8 2 | 1 7 5 | 
| 6 7 5 | 4 9 1 | 2 8 3 | 
------------------------- 
| 1 5 4 | 2 3 7 | 8 9 6 | 
| 3 6 9 | 8 4 5 | 7 2 1 | 
| 2 8 7 | 1 6 9 | 5 3 4 | 
------------------------- 
| 5 2 1 | 9 7 4 | 3 6 8 | 
| 4 3 8 | 5 2 6 | 9 1 7 | 
| 7 9 6 | 3 1 8 | 4 5 2 | 
------------------------- 


In [19]:
import numpy as np
from datetime import datetime


test7 = np.matrix([[0, 8, 0, 0, 0, 0, 0, 0, 0], 
                   [0, 0, 3, 6, 0, 0, 0, 0, 0],
                   [0, 7, 0, 0, 9, 0, 2, 0, 0],
                   [0, 5, 0, 0, 0, 7, 0, 0, 0],
                   [0, 0, 0, 0, 4, 5, 7, 0, 0], 
                   [0, 0, 0, 0, 0, 0, 0, 3, 0], 
                   [0, 0, 1, 0, 0, 0, 0, 6, 8],
                   [0, 0, 8, 5, 0, 0, 0, 1, 0],
                   [0, 9, 0, 0, 0, 0, 4, 0, 0]])
Print_Board(test7)
assign = create_assign_matrix(test7)

step = [0]

start_time = datetime.now()

solve_sudoku(test7, assign, step)

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

if goal_matrix(test7):
    print("Sudoku Completed")
    print ("Solution found in %s steps, "%(step[0]))
else:
    print("Solution Not Found")


Print_Board(test7)


-------------------------
|   8   |       |       | 
|     3 | 6     |       | 
|   7   |   9   | 2     | 
------------------------- 
|   5   |     7 |       | 
|       |   4 5 | 7     | 
|       |       |   3   | 
------------------------- 
|     1 |       |   6 8 | 
|     8 | 5     |   1   | 
|   9   |       | 4     | 
------------------------- 
Duration: 0:00:09.196057
Sudoku Completed
Solution found in 397 steps, 

-------------------------
| 5 8 4 | 7 2 1 | 6 9 3 | 
| 9 2 3 | 6 5 4 | 8 7 1 | 
| 1 7 6 | 3 9 8 | 2 5 4 | 
------------------------- 
| 8 5 2 | 9 3 7 | 1 4 6 | 
| 3 6 9 | 1 4 5 | 7 8 2 | 
| 4 1 7 | 2 8 6 | 9 3 5 | 
------------------------- 
| 2 3 1 | 4 7 9 | 5 6 8 | 
| 7 4 8 | 5 6 2 | 3 1 9 | 
| 6 9 5 | 8 1 3 | 4 2 7 | 
------------------------- 
