In [1]:
import random
import numpy as np
import math 
from random import choice
import statistics 

In [2]:

def Print_Board(board):

    print("\n-------------------------")

    for i in range(9):
        for j in range(9):
            if board[i, j] != 0:
                if j == 0:
                    print("|", end=" ")
                print(f"{board[i, j]} ", end="")
            else:
                if j == 0:
                    print("|", end=" ")
                print("  ", end="")
            if (j + 1) % 3 == 0:
                print("|", end=" ")
        if (i + 1) % 3 == 0:
            print("\n-------------------------", end=" ")
        print()
        

In [3]:
def domain_check(var): #checks if a variable is in the domain
    domain = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
    return np.any(domain == var)

In [4]:
#costraints
def constrain(value, x, y, matrix):
    #first checks if the value is in the domain
    if domain_check(value):
        
        #assigne a value not correct to not return false
        matrix[x, y] = -1
        
        #costrain submatrix
        submatrix = matrix[x//3*3:x//3*3+3, y//3*3:y//3*3+3]
        if np.any(submatrix == value):
            matrix[x, y] = value
            return False  
        
        #costrain column
        if np.any(matrix[:, y] == value):
            matrix[x, y] = value
            return False
        
        #costrain row
        if np.any(matrix[x, :] == value):
            matrix[x, y] = value
            return False 
        
        matrix[x, y] = value
        return True
    else:
        return False

In [5]:
#checks if the matrix is correct
def goal_matrix(matrix):
    
    if matrix.item(0) == -1:
        return False
    
    for x in range(9):
        for y in range(9):
            if constrain(matrix[x, y], x, y, matrix) == False & matrix[x, y] == 0:
                return False
    return True

In [6]:
def FixValues(matrix):
    for i in range(9):
        for j in range(9): 
            if matrix[i, j] != 0:
                matrix[i, j] = 1          
    return (matrix)

a = np.matrix([[3, 7, 0, 5, 0, 0, 0, 0, 6], 
               [0, 0, 0, 3, 6, 0, 0, 1, 2],
               [0, 0, 0, 0, 9, 1, 7, 5, 0],
               [0, 0, 0, 1, 5, 4, 0, 7, 0],
               [0, 0, 3, 0, 7, 0, 6, 0, 0], 
               [0, 5, 0, 6, 3, 8, 0, 0, 0], 
               [0, 6, 4, 9, 8, 0, 0, 0, 0],
               [5, 9, 0, 0, 2, 6, 0, 0, 0],
               [2, 0, 0, 0, 0, 5, 0, 6, 4]])
Print_Board(a)
Print_Board(FixValues(a))


-------------------------
| 3 7   | 5     |     6 | 
|       | 3 6   |   1 2 | 
|       |   9 1 | 7 5   | 
------------------------- 
|       | 1 5 4 |   7   | 
|     3 |   7   | 6     | 
|   5   | 6 3 8 |       | 
------------------------- 
|   6 4 | 9 8   |       | 
| 5 9   |   2 6 |       | 
| 2     |     5 |   6 4 | 
------------------------- 

-------------------------
| 1 1   | 1     |     1 | 
|       | 1 1   |   1 1 | 
|       |   1 1 | 1 1   | 
------------------------- 
|       | 1 1 1 |   1   | 
|     1 |   1   | 1     | 
|   1   | 1 1 1 |       | 
------------------------- 
|   1 1 | 1 1   |       | 
| 1 1   |   1 1 |       | 
| 1     |     1 |   1 1 | 
------------------------- 


In [7]:
def row_score(x, matrix):
    score = 0
    for j in range(9):
        val = matrix[x,j]
        matrix[x,j] = -1
        if np.any(matrix[x,] == val):
            score +=1
        matrix[x,j] = val
    score = np.sum(score)
    return score

In [8]:
def column_score(y, matrix):
    score = 0
    for i in range(9):
        val = matrix[i,y]
        matrix[i,y] = -1
        if np.any(matrix[:,y] == val):
            score +=1
        matrix[i,y] = val
    score = np.sum(score)
    return score

In [9]:
def score_board(matrix):

    score = 0
    
    for i in range(9):
        score += row_score(i, matrix)
    for j in range(9):
        score += column_score(j, matrix)
    
    return score
    
c = np.matrix([[8, 2, 7, 1, 5, 4, 3, 9, 6], 
               [9, 6, 5, 3, 2, 7, 1, 4, 8],
               [3, 4, 1, 6, 8, 9, 7, 5, 2],
               [5, 9, 3, 4, 6, 8, 2, 7, 1],
               [4, 7, 2, 5, 1, 3, 6, 8, 9], 
               [6, 1, 8, 9, 7, 2, 4, 3, 5], 
               [7, 8, 6, 2, 3, 5, 9, 1, 4],
               [1, 5, 4, 7, 9, 6, 8, 2, 3],
               [2, 3, 9, 8, 4, 1, 5, 6, 7]])
score_board(c)


0

In [10]:
def column_score(y, matrix):
    score = 0
    for i in range(9):
        val = matrix[i,y]
        matrix[i,y] = -1
        if np.any(matrix[:,y] == val):
            score +=1
        matrix[i,y] = val
    score = np.sum(score)
    return score

In [11]:
def random_fill_matrix(matrix):
        for i in range(9):
            for j in range(9):
                if matrix[i, j] == 0:
                    submatrix = matrix[i//3*3:i//3*3+3, j//3*3:j//3*3+3]
                    for value in range(9):                        
                        if not np.any(submatrix == value+1):
                            matrix[i, j] = value+1
        return matrix
a = np.matrix([[3, 7, 0, 5, 0, 0, 0, 0, 6], 
               [0, 0, 0, 3, 6, 0, 0, 1, 2],
               [0, 0, 0, 0, 9, 1, 7, 5, 0],
               [0, 0, 0, 1, 5, 4, 0, 7, 0],
               [0, 0, 3, 0, 7, 0, 6, 0, 0], 
               [0, 5, 0, 6, 3, 8, 0, 0, 0], 
               [0, 6, 4, 9, 8, 0, 0, 0, 0],
               [5, 9, 0, 0, 2, 6, 0, 0, 0],
               [2, 0, 0, 0, 0, 5, 0, 6, 4]])
Print_Board(random_fill_matrix(a))



-------------------------
| 3 7 9 | 5 8 7 | 9 8 6 | 
| 8 6 5 | 3 6 4 | 4 1 2 | 
| 4 2 1 | 2 9 1 | 7 5 3 | 
------------------------- 
| 9 8 7 | 1 5 4 | 9 7 8 | 
| 6 4 3 | 9 7 2 | 6 5 4 | 
| 2 5 1 | 6 3 8 | 3 2 1 | 
------------------------- 
| 8 6 4 | 9 8 7 | 9 8 7 | 
| 5 9 7 | 4 2 6 | 5 3 2 | 
| 2 3 1 | 3 1 5 | 1 6 4 | 
------------------------- 


In [12]:
def list_of_square(save_m):
    l_square = []
    for x in range(3):
        for y in range(3):
            submatrix = save_m[x*3:x*3+3, y*3:y*3+3]
            if np.count_nonzero(submatrix==0) > 1 & np.count_nonzero(submatrix==1) < 9 :
                l_square += [[x, y]]
            
    return l_square

a = np.matrix([[3, 7, 0, 5, 0, 0, 0, 0, 6], 
               [0, 0, 0, 3, 6, 0, 0, 1, 2],
               [0, 0, 0, 0, 9, 1, 7, 5, 0],
               [0, 0, 0, 1, 5, 4, 0, 7, 0],
               [0, 0, 3, 0, 7, 0, 6, 0, 0], 
               [0, 5, 0, 6, 3, 8, 0, 0, 0], 
               [0, 6, 4, 9, 8, 0, 0, 0, 0],
               [5, 9, 0, 0, 2, 6, 0, 0, 0],
               [2, 0, 0, 0, 0, 5, 0, 6, 4]])


list_of_square(FixValues(a))

[[0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2], [2, 0], [2, 1], [2, 2]]

In [13]:
def random_swap_two_element(old_matrix, save_m):
    """
    Generates "neighbor" board by randomly picking
    a square, then swapping two small squares within.
    """
    matrix = old_matrix.copy()
    l_square = list_of_square(save_m)
    
    if len(l_square) > 1:            
        num = random.randint(0, len(l_square)-1)
        square = l_square[num]
        x = square[0]
        y = square[1]   
        
        l_cells = []
        for i in range(x*3, x*3+3):
            for j in range(y*3, y*3+3):    
                if column_score(j, matrix) > 0: 
                        l_cells += [[i, j]]
                else:
                    if row_score(i, matrix) > 0:
                        l_cells += [[i, j]]
          
        if len(l_cells) > 1:  
            num = random.randint(0, len(l_cells)-1)
            cell1 = l_cells.pop(num)
            num = random.randint(0, len(l_cells)-1)
            cell2 = l_cells.pop(num)

            var = matrix[cell1[0], cell1[1]]
            matrix[cell1[0], cell1[1]] = matrix[cell2[0], cell2[1]]
            matrix[cell2[0], cell2[1]] = var
            
    return matrix

a = np.matrix([[3, 7, 0, 5, 0, 0, 0, 0, 6], 
               [0, 0, 0, 3, 6, 0, 0, 1, 2],
               [0, 0, 0, 0, 9, 1, 7, 5, 0],
               [0, 0, 0, 1, 5, 4, 0, 7, 0],
               [0, 0, 3, 0, 7, 0, 6, 0, 0], 
               [0, 5, 0, 6, 3, 8, 0, 0, 0], 
               [0, 6, 4, 9, 8, 0, 0, 0, 0],
               [5, 9, 0, 0, 2, 6, 0, 0, 0],
               [2, 0, 0, 0, 0, 5, 0, 6, 4]])
save = FixValues(a.copy())
random_fill_matrix(a)
Print_Board(a)
b = random_swap_two_element(a, save)
Print_Board(b)
print(b - a)


-------------------------
| 3 7 9 | 5 8 7 | 9 8 6 | 
| 8 6 5 | 3 6 4 | 4 1 2 | 
| 4 2 1 | 2 9 1 | 7 5 3 | 
------------------------- 
| 9 8 7 | 1 5 4 | 9 7 8 | 
| 6 4 3 | 9 7 2 | 6 5 4 | 
| 2 5 1 | 6 3 8 | 3 2 1 | 
------------------------- 
| 8 6 4 | 9 8 7 | 9 8 7 | 
| 5 9 7 | 4 2 6 | 5 3 2 | 
| 2 3 1 | 3 1 5 | 1 6 4 | 
------------------------- 

-------------------------
| 3 7 9 | 5 8 7 | 9 8 6 | 
| 8 6 5 | 3 6 4 | 4 1 2 | 
| 4 2 1 | 2 9 1 | 7 5 3 | 
------------------------- 
| 9 8 3 | 1 5 4 | 9 7 8 | 
| 6 4 7 | 9 7 2 | 6 5 4 | 
| 2 5 1 | 6 3 8 | 3 2 1 | 
------------------------- 
| 8 6 4 | 9 8 7 | 9 8 7 | 
| 5 9 7 | 4 2 6 | 5 3 2 | 
| 2 3 1 | 3 1 5 | 1 6 4 | 
------------------------- 
[[ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0 -4  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]]


In [14]:
def ChooseNewState (currentSudoku, fixedSudoku, sigma):
    newSudoku = random_swap_two_element(currentSudoku, fixedSudoku)
    currentCost = score_board(currentSudoku)
    newCost = score_board(newSudoku)
    costDifference = newCost - currentCost
    rho = math.exp(-costDifference/sigma)
    if(np.random.uniform(1,0,1) < rho):
        return newSudoku
    return currentSudoku

In [15]:
def ChooseNumberOfItterations(fixed_sudoku):
    numberOfItterations = 0
    for i in range (0,9):
        for j in range (0,9):
            if fixed_sudoku[i,j] != 0:
                numberOfItterations += 1
    return numberOfItterations


In [16]:
def solveSudoku (sudoku):
    #criteria to stop the lopp
    solutionFound = 0
    
    #fix the value of sudoku to 1
    fixedSudoku = np.copy(sudoku)        
    FixValues(fixedSudoku)
    
    #number of value of fixedSudoku = 1
    itterations = ChooseNumberOfItterations(fixedSudoku)
    
    #steps count
    step = 0
    
    # = 0 solution not found, = 1 solution found
    while (solutionFound == 0):
        
        #cooling factor
        decreaseFactor = 0.999
        
        
        stuckCount = 0   
        
        #random fill the matrix
        tmpSudoku = random_fill_matrix(np.copy(sudoku))        
        score = score_board(tmpSudoku)
        
        #temperature
        T = 0.4
        
        #Cost Function Check
        if score <= 0:
            solutionFound = 1

        #loop until you didn't find a solution
        while solutionFound == 0:
            
            #old state score
            previousScore = score
            
            #search for a new state
            for i in range (0, itterations+1):
                
                tmpSudoku = ChooseNewState(tmpSudoku, fixedSudoku, T)               
                
                score = score_board(tmpSudoku)
                if score <= 0:
                    solutionFound = 1
                    break
            
            if step % 10 == 0:
                print ("Iteration %s,    \tT = %.5f, \tbest_score = %s, "%(step, T, score))
            step += 1  
            
            #cooling the  temperature
            T *= decreaseFactor
            
            if score <= 0:
                solutionFound = 1
                break
            
            #if the solution is the same add stuckCounter
            if score >= previousScore:
                stuckCount += 1
            else:
                stuckCount = 0
            #if we are stuck in a local minimum we increase the temperature
            if (stuckCount > 80):
                stuckCount = 0
                T += 0.2
            
            #Solution Found Stop the Loop
            if(score_board(tmpSudoku)==0):
                solutionFound = 1
                break
                
    print ("Solution found in %s steps, "%(step))
    return(tmpSudoku)

In [17]:
from datetime import datetime

test0 = np.matrix([[3, 7, 0, 5, 0, 0, 0, 0, 6], 
               [0, 0, 0, 3, 6, 0, 0, 1, 2],
               [0, 0, 0, 0, 9, 1, 7, 5, 0],
               [0, 0, 0, 1, 5, 4, 0, 7, 0],
               [0, 0, 3, 0, 7, 0, 6, 0, 0], 
               [0, 5, 0, 6, 3, 8, 0, 0, 0], 
               [0, 6, 4, 9, 8, 0, 0, 0, 0],
               [5, 9, 0, 0, 2, 6, 0, 0, 0],
               [2, 0, 0, 0, 0, 5, 0, 6, 4]])

Print_Board(test0)

start_time = datetime.now()

result = solveSudoku(test0)

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

if goal_matrix(result):
    print("Sudoku Completed")
else:
    print("Solution Not Found")


Print_Board(result)


-------------------------
| 3 7   | 5     |     6 | 
|       | 3 6   |   1 2 | 
|       |   9 1 | 7 5   | 
------------------------- 
|       | 1 5 4 |   7   | 
|     3 |   7   | 6     | 
|   5   | 6 3 8 |       | 
------------------------- 
|   6 4 | 9 8   |       | 
| 5 9   |   2 6 |       | 
| 2     |     5 |   6 4 | 
------------------------- 
Iteration 0,    	T = 0.40000, 	best_score = 58, 
Iteration 10,    	T = 0.39602, 	best_score = 12, 
Iteration 20,    	T = 0.39208, 	best_score = 4, 
Solution found in 22 steps, 
Duration: 0:00:03.558116
Sudoku Completed

-------------------------
| 3 2 7 | 8 1 4 | 5 6 9 | 
| 4 5 9 | 3 6 2 | 8 1 7 | 
| 8 6 1 | 5 7 9 | 4 2 3 | 
------------------------- 
| 9 8 2 | 1 4 5 | 3 7 6 | 
| 6 1 3 | 9 8 7 | 2 4 5 | 
| 7 4 5 | 6 2 3 | 1 9 8 | 
------------------------- 
| 1 9 8 | 2 5 6 | 7 3 4 | 
| 5 7 6 | 4 3 1 | 9 8 2 | 
| 2 3 4 | 7 9 8 | 6 5 1 | 
------------------------- 


In [18]:
import numpy as np
from datetime import datetime


test1 = np.matrix([[0, 1, 6, 3, 0, 8, 4, 2, 0], 
                   [8, 4, 0, 0, 0, 7, 3, 0, 0],
                   [3, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 6, 0, 9, 4, 0, 8, 0, 2],
                   [0, 8, 1, 0, 3, 0, 7, 9, 0], 
                   [9, 0, 3, 0, 7, 6, 0, 4, 0], 
                   [0, 0, 0, 0, 0, 0, 0, 0, 3],
                   [0, 0, 5, 7, 0, 0, 0, 6, 8],
                   [0, 7, 8, 1, 0, 3, 2, 5, 0]])
Print_Board(test1)

start_time = datetime.now()

result = solveSudoku(test1)

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

if goal_matrix(result):
    print("Sudoku Completed")
else:
    print("Solution Not Found")


Print_Board(result)


-------------------------
|   1 6 | 3   8 | 4 2   | 
| 8 4   |     7 | 3     | 
| 3     |       |       | 
------------------------- 
|   6   | 9 4   | 8   2 | 
|   8 1 |   3   | 7 9   | 
| 9   3 |   7 6 |   4   | 
------------------------- 
|       |       |     3 | 
|     5 | 7     |   6 8 | 
|   7 8 | 1   3 | 2 5   | 
------------------------- 
Iteration 0,    	T = 0.40000, 	best_score = 55, 
Iteration 10,    	T = 0.39602, 	best_score = 14, 
Iteration 20,    	T = 0.39208, 	best_score = 8, 
Iteration 30,    	T = 0.38817, 	best_score = 4, 
Iteration 40,    	T = 0.38431, 	best_score = 4, 
Solution found in 43 steps, 
Duration: 0:00:08.266017
Sudoku Completed

-------------------------
| 6 5 7 | 1 3 8 | 2 9 4 | 
| 3 4 9 | 6 2 7 | 5 1 8 | 
| 8 1 2 | 4 5 9 | 6 3 7 | 
------------------------- 
| 7 8 6 | 3 1 5 | 4 2 9 | 
| 4 3 5 | 8 9 2 | 1 7 6 | 
| 9 2 1 | 7 4 6 | 3 8 5 | 
------------------------- 
| 2 6 4 | 9 8 1 | 7 5 3 | 
| 5 9 3 | 2 7 4 | 8 6 1 | 
| 1 7 8 | 5 6 3 | 9 4 2 | 
--------

In [19]:
import numpy as np
from datetime import datetime


test2 = np.matrix([[0, 0, 2, 0, 3, 0, 0, 0, 8], 
                   [0, 0, 0, 0, 0, 8, 0, 0, 0],
                   [0, 3, 1, 0, 2, 0, 0, 0, 0],
                   [0, 6, 0, 0, 5, 0, 2, 7, 0],
                   [0, 1, 0, 0, 0, 0, 0, 5, 0], 
                   [2, 0, 4, 0, 6, 0, 0, 3, 1], 
                   [0, 0, 0, 0, 8, 0, 6, 0, 5],
                   [0, 0, 0, 0, 0, 0, 0, 1, 3],
                   [0, 0, 5, 3, 1, 0, 4, 0, 0]])
Print_Board(test2)
start_time = datetime.now()

result = solveSudoku(test2)

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

if goal_matrix(result):
    print("Sudoku Completed")
else:
    print("Solution Not Found")


Print_Board(result)


-------------------------
|     2 |   3   |     8 | 
|       |     8 |       | 
|   3 1 |   2   |       | 
------------------------- 
|   6   |   5   | 2 7   | 
|   1   |       |   5   | 
| 2   4 |   6   |   3 1 | 
------------------------- 
|       |   8   | 6   5 | 
|       |       |   1 3 | 
|     5 | 3 1   | 4     | 
------------------------- 
Iteration 0,    	T = 0.40000, 	best_score = 82, 
Iteration 10,    	T = 0.39602, 	best_score = 16, 
Iteration 20,    	T = 0.39208, 	best_score = 14, 
Iteration 30,    	T = 0.38817, 	best_score = 11, 
Iteration 40,    	T = 0.38431, 	best_score = 4, 
Solution found in 43 steps, 
Duration: 0:00:05.239858
Sudoku Completed

-------------------------
| 9 7 1 | 6 3 5 | 8 4 2 | 
| 3 2 5 | 4 9 8 | 1 6 7 | 
| 4 8 6 | 7 2 1 | 9 5 3 | 
------------------------- 
| 8 1 3 | 9 5 7 | 6 2 4 | 
| 2 6 9 | 8 4 3 | 5 7 1 | 
| 7 5 4 | 1 6 2 | 3 8 9 | 
------------------------- 
| 6 3 2 | 5 7 9 | 4 1 8 | 
| 1 4 7 | 3 8 6 | 2 9 5 | 
| 5 9 8 | 2 1 4 | 7 3 6 | 
------

In [20]:
import numpy as np
from datetime import datetime


test3 = np.matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0], 
                   [0, 0, 8, 0, 0, 0, 0, 4, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 6, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0], 
                   [0, 0, 0, 0, 0, 0, 0, 0, 0], 
                   [2, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 2, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0]])
Print_Board(test3)

start_time = datetime.now()

result = solveSudoku(test3)

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

if goal_matrix(result):
    print("Sudoku Completed")
else:
    print("Solution Not Found")


Print_Board(result)


-------------------------
|       |       |       | 
|     8 |       |   4   | 
|       |       |       | 
------------------------- 
|       |     6 |       | 
|       |       |       | 
|       |       |       | 
------------------------- 
| 2     |       |       | 
|       |       | 2     | 
|       |       |       | 
------------------------- 
Iteration 0,    	T = 0.40000, 	best_score = 118, 
Iteration 10,    	T = 0.39602, 	best_score = 63, 
Iteration 20,    	T = 0.39208, 	best_score = 52, 
Iteration 30,    	T = 0.38817, 	best_score = 38, 
Iteration 40,    	T = 0.38431, 	best_score = 23, 
Iteration 50,    	T = 0.38048, 	best_score = 20, 
Iteration 60,    	T = 0.37669, 	best_score = 20, 
Iteration 70,    	T = 0.37294, 	best_score = 16, 
Iteration 80,    	T = 0.36923, 	best_score = 16, 
Iteration 90,    	T = 0.36556, 	best_score = 12, 
Iteration 100,    	T = 0.36192, 	best_score = 8, 
Iteration 110,    	T = 0.35831, 	best_score = 4, 
Iteration 120,    	T = 0.35475, 	best_score = 4, 

In [21]:
import numpy as np
from datetime import datetime


test4 = np.matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0], 
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0], 
                   [0, 0, 0, 0, 0, 0, 0, 0, 0], 
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 0, 0, 0, 0]])
Print_Board(test4)

start_time = datetime.now()

result = solveSudoku(test4)

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

if goal_matrix(result):
    print("Sudoku Completed")
else:
    print("Solution Not Found")


Print_Board(result)


-------------------------
|       |       |       | 
|       |       |       | 
|       |       |       | 
------------------------- 
|       |       |       | 
|       |       |       | 
|       |       |       | 
------------------------- 
|       |       |       | 
|       |       |       | 
|       |       |       | 
------------------------- 
Iteration 0,    	T = 0.40000, 	best_score = 158, 
Iteration 10,    	T = 0.39602, 	best_score = 134, 
Iteration 20,    	T = 0.39208, 	best_score = 119, 
Iteration 30,    	T = 0.38817, 	best_score = 100, 
Iteration 40,    	T = 0.38431, 	best_score = 94, 
Iteration 50,    	T = 0.38048, 	best_score = 79, 
Iteration 60,    	T = 0.37669, 	best_score = 65, 
Iteration 70,    	T = 0.37294, 	best_score = 65, 
Iteration 80,    	T = 0.36923, 	best_score = 64, 
Iteration 90,    	T = 0.36556, 	best_score = 58, 
Iteration 100,    	T = 0.36192, 	best_score = 56, 
Iteration 110,    	T = 0.35831, 	best_score = 57, 
Iteration 120,    	T = 0.35475, 	best_score 

Iteration 1530,    	T = 0.89021, 	best_score = 16, 
Iteration 1540,    	T = 0.88135, 	best_score = 16, 
Iteration 1550,    	T = 0.87257, 	best_score = 16, 
Iteration 1560,    	T = 0.86389, 	best_score = 16, 
Iteration 1570,    	T = 0.85529, 	best_score = 16, 
Iteration 1580,    	T = 1.04657, 	best_score = 16, 
Iteration 1590,    	T = 1.03615, 	best_score = 19, 
Iteration 1600,    	T = 1.02584, 	best_score = 19, 
Iteration 1610,    	T = 1.01563, 	best_score = 19, 
Iteration 1620,    	T = 1.00552, 	best_score = 19, 
Iteration 1630,    	T = 0.99551, 	best_score = 20, 
Iteration 1640,    	T = 0.98560, 	best_score = 22, 
Iteration 1650,    	T = 0.97578, 	best_score = 26, 
Iteration 1660,    	T = 0.96607, 	best_score = 26, 
Iteration 1670,    	T = 0.95645, 	best_score = 26, 
Iteration 1680,    	T = 0.94693, 	best_score = 26, 
Iteration 1690,    	T = 0.93750, 	best_score = 25, 
Iteration 1700,    	T = 0.92817, 	best_score = 22, 
Iteration 1710,    	T = 0.91893, 	best_score = 22, 
Iteration 17

Iteration 3160,    	T = 1.20519, 	best_score = 26, 
Iteration 3170,    	T = 1.19319, 	best_score = 26, 
Iteration 3180,    	T = 1.18131, 	best_score = 22, 
Iteration 3190,    	T = 1.16955, 	best_score = 20, 
Iteration 3200,    	T = 1.15791, 	best_score = 20, 
Iteration 3210,    	T = 1.14638, 	best_score = 24, 
Iteration 3220,    	T = 1.13497, 	best_score = 24, 
Iteration 3230,    	T = 1.12367, 	best_score = 28, 
Iteration 3240,    	T = 1.11248, 	best_score = 24, 
Iteration 3250,    	T = 1.10141, 	best_score = 24, 
Iteration 3260,    	T = 1.09044, 	best_score = 24, 
Iteration 3270,    	T = 1.07959, 	best_score = 24, 
Iteration 3280,    	T = 1.06884, 	best_score = 24, 
Iteration 3290,    	T = 1.05820, 	best_score = 24, 
Iteration 3300,    	T = 1.04767, 	best_score = 24, 
Iteration 3310,    	T = 1.03724, 	best_score = 28, 
Iteration 3320,    	T = 1.22691, 	best_score = 28, 
Iteration 3330,    	T = 1.21470, 	best_score = 28, 
Iteration 3340,    	T = 1.20260, 	best_score = 30, 
Iteration 33

Iteration 4750,    	T = 1.39969, 	best_score = 4, 
Iteration 4760,    	T = 1.38576, 	best_score = 4, 
Iteration 4770,    	T = 1.37196, 	best_score = 4, 
Iteration 4780,    	T = 1.35830, 	best_score = 4, 
Iteration 4790,    	T = 1.34478, 	best_score = 4, 
Iteration 4800,    	T = 1.33139, 	best_score = 4, 
Iteration 4810,    	T = 1.31814, 	best_score = 4, 
Iteration 4820,    	T = 1.50382, 	best_score = 4, 
Solution found in 4826 steps, 
Duration: 0:00:38.784919
Sudoku Completed

-------------------------
| 8 7 5 | 4 1 2 | 9 6 3 | 
| 1 3 6 | 9 5 8 | 2 4 7 | 
| 4 9 2 | 6 7 3 | 1 8 5 | 
------------------------- 
| 5 1 7 | 8 6 4 | 3 9 2 | 
| 3 8 4 | 5 2 9 | 6 7 1 | 
| 6 2 9 | 7 3 1 | 8 5 4 | 
------------------------- 
| 9 6 3 | 1 4 7 | 5 2 8 | 
| 2 4 8 | 3 9 5 | 7 1 6 | 
| 7 5 1 | 2 8 6 | 4 3 9 | 
------------------------- 


In [22]:
import numpy as np
from datetime import datetime



test5 = np.matrix([[0, 2, 0, 0, 0, 0, 0, 0, 0], 
                   [0, 0, 0, 6, 0, 0, 0, 0, 3],
                   [0, 7, 4, 0, 8, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 3, 0, 0, 2],
                   [0, 8, 0, 0, 4, 0, 0, 1, 0], 
                   [6, 0, 0, 5, 0, 0, 0, 0, 0], 
                   [0, 0, 0, 0, 1, 0, 7, 8, 0],
                   [5, 0, 0, 0, 0, 0, 0, 0, 0],
                   [0, 0, 0, 0, 0, 9, 0, 4, 0]])
Print_Board(test5)

start_time = datetime.now()

result = solveSudoku(test5)

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

if goal_matrix(result):
    print("Sudoku Completed")
else:
    print("Solution Not Found")


Print_Board(result)


-------------------------
|   2   |       |       | 
|       | 6     |     3 | 
|   7 4 |   8   |       | 
------------------------- 
|       |     3 |     2 | 
|   8   |   4   |   1   | 
| 6     | 5     |       | 
------------------------- 
|       |   1   | 7 8   | 
| 5     |       |       | 
|       |     9 |   4   | 
------------------------- 
Iteration 0,    	T = 0.40000, 	best_score = 78, 
Iteration 10,    	T = 0.39602, 	best_score = 36, 
Iteration 20,    	T = 0.39208, 	best_score = 26, 
Iteration 30,    	T = 0.38817, 	best_score = 16, 
Iteration 40,    	T = 0.38431, 	best_score = 8, 
Iteration 50,    	T = 0.38048, 	best_score = 8, 
Iteration 60,    	T = 0.37669, 	best_score = 8, 
Iteration 70,    	T = 0.37294, 	best_score = 8, 
Iteration 80,    	T = 0.36923, 	best_score = 4, 
Solution found in 83 steps, 
Duration: 0:00:09.676434
Sudoku Completed

-------------------------
| 6 5 2 | 3 9 1 | 8 4 7 | 
| 3 8 9 | 7 4 5 | 6 2 1 | 
| 4 7 1 | 6 8 2 | 3 9 5 | 
------------------------- 

In [23]:
import numpy as np
from datetime import datetime



test6 = np.matrix([[8, 0, 0, 0, 0, 0, 0, 0, 0], 
                   [0, 0, 3, 6, 0, 0, 0, 0, 0],
                   [0, 7, 0, 0, 9, 0, 2, 0, 0],
                   [0, 5, 0, 0, 0, 7, 0, 0, 0],
                   [0, 0, 0, 0, 4, 5, 7, 0, 0], 
                   [0, 0, 0, 1, 0, 0, 0, 3, 0], 
                   [0, 0, 1, 0, 0, 0, 0, 6, 8],
                   [0, 0, 8, 5, 0, 0, 0, 1, 0],
                   [0, 9, 0, 0, 0, 0, 4, 0, 0]])
Print_Board(test6)
start_time = datetime.now()

result = solveSudoku(test6)

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

if goal_matrix(result):
    print("Sudoku Completed")
else:
    print("Solution Not Found")


Print_Board(result)


-------------------------
| 8     |       |       | 
|     3 | 6     |       | 
|   7   |   9   | 2     | 
------------------------- 
|   5   |     7 |       | 
|       |   4 5 | 7     | 
|       | 1     |   3   | 
------------------------- 
|     1 |       |   6 8 | 
|     8 | 5     |   1   | 
|   9   |       | 4     | 
------------------------- 
Iteration 0,    	T = 0.40000, 	best_score = 80, 
Iteration 10,    	T = 0.39602, 	best_score = 24, 
Iteration 20,    	T = 0.39208, 	best_score = 15, 
Iteration 30,    	T = 0.38817, 	best_score = 12, 
Iteration 40,    	T = 0.38431, 	best_score = 8, 
Iteration 50,    	T = 0.38048, 	best_score = 0, 
Solution found in 51 steps, 
Duration: 0:00:06.133997
Sudoku Completed

-------------------------
| 8 3 6 | 2 5 9 | 1 4 7 | 
| 7 2 5 | 1 4 8 | 6 3 9 | 
| 4 9 1 | 3 6 7 | 2 5 8 | 
------------------------- 
| 3 1 4 | 8 9 6 | 5 7 2 | 
| 6 5 2 | 4 7 3 | 9 8 1 | 
| 9 8 7 | 5 1 2 | 3 6 4 | 
------------------------- 
| 1 6 9 | 7 8 5 | 4 2 3 | 
| 2 4 8 | 6

In [24]:
import numpy as np
from datetime import datetime


test7 = np.matrix([[0, 8, 0, 0, 0, 0, 0, 0, 0], 
                   [0, 0, 3, 6, 0, 0, 0, 0, 0],
                   [0, 7, 0, 0, 9, 0, 2, 0, 0],
                   [0, 5, 0, 0, 0, 7, 0, 0, 0],
                   [0, 0, 0, 0, 4, 5, 7, 0, 0], 
                   [0, 0, 0, 0, 0, 0, 0, 3, 0], 
                   [0, 0, 1, 0, 0, 0, 0, 6, 8],
                   [0, 0, 8, 5, 0, 0, 0, 1, 0],
                   [0, 9, 0, 0, 0, 0, 4, 0, 0]])
Print_Board(test7)

start_time = datetime.now()

result = solveSudoku(test7)

end_time = datetime.now()
print('Duration: {}'.format(end_time - start_time))

if goal_matrix(result):
    print("Sudoku Completed")
else:
    print("Solution Not Found")


Print_Board(result)


-------------------------
|   8   |       |       | 
|     3 | 6     |       | 
|   7   |   9   | 2     | 
------------------------- 
|   5   |     7 |       | 
|       |   4 5 | 7     | 
|       |       |   3   | 
------------------------- 
|     1 |       |   6 8 | 
|     8 | 5     |   1   | 
|   9   |       | 4     | 
------------------------- 
Iteration 0,    	T = 0.40000, 	best_score = 90, 
Iteration 10,    	T = 0.39602, 	best_score = 28, 
Iteration 20,    	T = 0.39208, 	best_score = 20, 
Iteration 30,    	T = 0.38817, 	best_score = 12, 
Iteration 40,    	T = 0.38431, 	best_score = 12, 
Iteration 50,    	T = 0.38048, 	best_score = 6, 
Iteration 60,    	T = 0.37669, 	best_score = 4, 
Iteration 70,    	T = 0.37294, 	best_score = 4, 
Solution found in 75 steps, 
Duration: 0:00:07.819047
Sudoku Completed

-------------------------
| 7 6 3 | 2 1 9 | 8 5 4 | 
| 2 8 5 | 4 6 7 | 1 9 3 | 
| 9 1 4 | 8 3 5 | 2 7 6 | 
------------------------- 
| 8 4 7 | 1 5 6 | 3 2 9 | 
| 1 9 2 | 3 4 8 | 5 

In [25]:
r = []